### ISSUE TITLE
Does not work on local files

### ISSUE THREAD

**Issue by bellwood** [jchamet/html-table-sort#3]
With a file saved on my desktop loaded in Chrome as:

file:///Users/me/Desktop/example.html

...it does not work.

If I take that exact file and drop it on a domain:

http://example-domain.com/example.html

...it now works.

Thank you for your support =)

**Comment by jchamet** [comment]
Hm, the extension doesn't rely on any external libraries... I'll look into it!

**Comment by bellwood** [comment]
This might be related:

http://stackoverflow.com/questions/20748630/load-local-javascript-file-in-chrome-for-testing

Not specifically calling local .js files but the browser allowing JS on a local file

**Comment by dlh3** [comment]
This issue is ancient now, but this is a Chrome security feature to protect you from extensions reading files on your local filesystem.

You can allow specific extensions to access file URLs (local files) in the individual extension's settings (chrome://extensions/?id=bpgbkjehkeffmmjfmdlmjjlffgkdcljp).  See the toggle at the bottom of this screenshot.

![image](https://user-images.githubusercontent.com/648035/48334299-fdfdcf00-e60e-11e8-9b75-c91e44767e30.png)
